import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Navbar from "../component/Navbar";
import { Suspense } from "react";
import MarqueeHeadline from "../component/Marquee";

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["bengali"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${hindSiliguri.className} h-full antialiased `}
    >
          <body className="min-h-full flex flex-col ">
    
         
      <Navbar />
  
              <div>
     
        <MarqueeHeadline />
     
    </div>
      
        
  
        
        
        {children}
        
        </body>
    </html>
  );
}
